// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxcTEle4SHslwuQtjyRwQXGyjJmDCBwrc',
    appId: '1:663860717703:web:9a627f08a44f4a9f033022',
    messagingSenderId: '663860717703',
    projectId: 'metro-9be3d',
    authDomain: 'metro-9be3d.firebaseapp.com',
    storageBucket: 'metro-9be3d.firebasestorage.app',
    measurementId: 'G-1FK1RPGQX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3M13y_23YiotnPJYlOzUh3SypFRXAzro',
    appId: '1:663860717703:android:c7010fb84008b58d033022',
    messagingSenderId: '663860717703',
    projectId: 'metro-9be3d',
    storageBucket: 'metro-9be3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4HxDKeWJmLdJv4LHM3710LW5KyWeEM4',
    appId: '1:663860717703:ios:231b66bec3c41c09033022',
    messagingSenderId: '663860717703',
    projectId: 'metro-9be3d',
    storageBucket: 'metro-9be3d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb4HxDKeWJmLdJv4LHM3710LW5KyWeEM4',
    appId: '1:663860717703:ios:231b66bec3c41c09033022',
    messagingSenderId: '663860717703',
    projectId: 'metro-9be3d',
    storageBucket: 'metro-9be3d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxcTEle4SHslwuQtjyRwQXGyjJmDCBwrc',
    appId: '1:663860717703:web:8085f1c8b1ffc192033022',
    messagingSenderId: '663860717703',
    projectId: 'metro-9be3d',
    authDomain: 'metro-9be3d.firebaseapp.com',
    storageBucket: 'metro-9be3d.firebasestorage.app',
    measurementId: 'G-V9138JDY1N',
  );
}
